POST http://localhost:7988/graphs/data
Content-Type: application/json

{
    "propertyID": "6-YaNQcL",
    "startDateTime": "2020-01-23T20:00:00.242Z",
    "endDateTime": "2020-02-25T20:20:49.242Z",
    "params": ""
}
