  
POST http://localhost:7988/property/create
Content-Type: application/json

{
  "name": "MinD Webs",
  "uniqueCode": "dipanroy@mindwebs.org",
  "location": "Madhyamgram",
  "latitude": "88.12345678",
  "longitude": "75.12345678",
  "elevation": "10",
  "area": "0.72",
  "adminName": "Dipan Roy"
}